/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maquette;

/**
 *
 * @author Poste8
 */
public class FenFicheClient extends javax.swing.JFrame {

    /**
     * Creates new form FenFicheClient
     */
    public FenFicheClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jImprimer = new javax.swing.JLabel();
        jBtnSauvegarder = new javax.swing.JLabel();
        jBtnAnnuler = new javax.swing.JLabel();
        jApercuAvImp = new javax.swing.JLabel();
        jExporter = new javax.swing.JLabel();
        JRetMenuClients = new javax.swing.JLabel();
        jAjoutClient = new javax.swing.JLabel();
        jLab_code = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jImprimer.setForeground(new java.awt.Color(255, 255, 255));
        jImprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/imprimer.png"))); // NOI18N
        jImprimer.setText("Imprimer");
        getContentPane().add(jImprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jBtnSauvegarder.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSauvegarder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/ajouter.png"))); // NOI18N
        jBtnSauvegarder.setText("Sauvegarder");
        getContentPane().add(jBtnSauvegarder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 40));

        jBtnAnnuler.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAnnuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/annuler.png"))); // NOI18N
        jBtnAnnuler.setText("Annuler");
        getContentPane().add(jBtnAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jApercuAvImp.setForeground(new java.awt.Color(255, 255, 255));
        jApercuAvImp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/apercu2.png"))); // NOI18N
        jApercuAvImp.setText("Aperçu avant impression");
        getContentPane().add(jApercuAvImp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 170, -1));

        jExporter.setForeground(new java.awt.Color(255, 255, 255));
        jExporter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/exporter.png"))); // NOI18N
        jExporter.setText("Exporter");
        getContentPane().add(jExporter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        JRetMenuClients.setForeground(new java.awt.Color(255, 255, 255));
        JRetMenuClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/retour.png"))); // NOI18N
        JRetMenuClients.setText("Retour au menu CLients");
        getContentPane().add(JRetMenuClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jAjoutClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jAjoutClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/client.png"))); // NOI18N
        jAjoutClient.setText("Ajout d'un client");
        getContentPane().add(jAjoutClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jLab_code.setText("Code");
        getContentPane().add(jLab_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.fond/fond.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 810, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenFicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenFicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenFicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenFicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenFicheClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JRetMenuClients;
    private javax.swing.JLabel jAjoutClient;
    private javax.swing.JLabel jApercuAvImp;
    private javax.swing.JLabel jBtnAnnuler;
    private javax.swing.JLabel jBtnSauvegarder;
    private javax.swing.JLabel jExporter;
    private javax.swing.JLabel jImprimer;
    private javax.swing.JLabel jLab_code;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
