/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maquette;

/**
 *
 * @author Cyril
 */
public class FenTableFacture extends javax.swing.JPanel {

    /**
     * Creates new form FenTableFacture
     */
    public FenTableFacture() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab_Imprimer = new javax.swing.JLabel();
        jLab_Aperçu = new javax.swing.JLabel();
        jLab_Exporter = new javax.swing.JLabel();
        jLab_Supprimer = new javax.swing.JLabel();
        jLab_Retour = new javax.swing.JLabel();
        jLab_GestionFacture = new javax.swing.JLabel();
        jScrollPane_Gestion = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_Total = new javax.swing.JButton();
        jTextField_Total = new javax.swing.JTextField();
        jButton_RechercherFacture = new javax.swing.JButton();
        jTextField_GestionFacture = new javax.swing.JTextField();
        jLab_fond = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Imprimer.setForeground(java.awt.Color.white);
        jLab_Imprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/imprimer3.png"))); // NOI18N
        jLab_Imprimer.setText("Imprimer");
        add(jLab_Imprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLab_Aperçu.setForeground(java.awt.Color.white);
        jLab_Aperçu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/apercu3.png"))); // NOI18N
        jLab_Aperçu.setText("Aperçu");
        add(jLab_Aperçu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLab_Exporter.setForeground(java.awt.Color.white);
        jLab_Exporter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/export3.png"))); // NOI18N
        jLab_Exporter.setText("Exporter");
        add(jLab_Exporter, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLab_Supprimer.setForeground(java.awt.Color.white);
        jLab_Supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/supprimer2.png"))); // NOI18N
        jLab_Supprimer.setText("Supprimer");
        add(jLab_Supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLab_Retour.setForeground(java.awt.Color.white);
        jLab_Retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/retour.png"))); // NOI18N
        jLab_Retour.setText("Retour");
        add(jLab_Retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLab_GestionFacture.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLab_GestionFacture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/odt.png"))); // NOI18N
        jLab_GestionFacture.setText("Gestion des factures");
        add(jLab_GestionFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_Gestion.setViewportView(jTable1);

        add(jScrollPane_Gestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, 90));

        jButton_Total.setText("Total");
        add(jButton_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 70, 40));
        add(jTextField_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 80, 30));

        jButton_RechercherFacture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/chercheAssiste.png"))); // NOI18N
        jButton_RechercherFacture.setText("Rechercher une facture");
        add(jButton_RechercherFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));
        add(jTextField_GestionFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 80, 30));

        jLab_fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.fond/fondGeneral.jpg"))); // NOI18N
        add(jLab_fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 780, 450));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_RechercherFacture;
    private javax.swing.JButton jButton_Total;
    private javax.swing.JLabel jLab_Aperçu;
    private javax.swing.JLabel jLab_Exporter;
    private javax.swing.JLabel jLab_GestionFacture;
    private javax.swing.JLabel jLab_Imprimer;
    private javax.swing.JLabel jLab_Retour;
    private javax.swing.JLabel jLab_Supprimer;
    private javax.swing.JLabel jLab_fond;
    private javax.swing.JScrollPane jScrollPane_Gestion;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_GestionFacture;
    private javax.swing.JTextField jTextField_Total;
    // End of variables declaration//GEN-END:variables
}
