/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maquette;

/**
 *
 * @author Poste8
 */
public class FenFicheClient extends javax.swing.JFrame {

    /**
     * Creates new form FenFicheClient
     */
    public FenFicheClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jImprimer = new javax.swing.JLabel();
        jBtnSauvegarder = new javax.swing.JLabel();
        jBtnAnnuler = new javax.swing.JLabel();
        jApercuAvImp = new javax.swing.JLabel();
        jExporter = new javax.swing.JLabel();
        JRetMenuClients = new javax.swing.JLabel();
        jAjoutClient = new javax.swing.JLabel();
        jPan_AjoutClient = new javax.swing.JPanel();
        jLab = new javax.swing.JLabel();
        jLab_Remarques = new javax.swing.JLabel();
        jLab_Nom = new javax.swing.JLabel();
        jLab_Code = new javax.swing.JLabel();
        jLab_Prénom = new javax.swing.JLabel();
        jLab_DateCreation = new javax.swing.JLabel();
        jLab_Adresse = new javax.swing.JLabel();
        jLab_Mobile = new javax.swing.JLabel();
        jLab_TelFixe = new javax.swing.JLabel();
        jLab_CodePostal = new javax.swing.JLabel();
        jLab_Ville = new javax.swing.JLabel();
        jLab_Email = new javax.swing.JLabel();
        jLab_CarteFidélité = new javax.swing.JLabel();
        jTxt_Adresse = new javax.swing.JTextField();
        jTxtField_Prénom = new javax.swing.JTextField();
        jTxtField_Nom = new javax.swing.JTextField();
        jTxtField_Email = new javax.swing.JTextField();
        jTxtField_DateCreation = new javax.swing.JTextField();
        jTxtField_Code = new javax.swing.JTextField();
        jTxtField_TelFixe = new javax.swing.JTextField();
        jTxtField_CodePostal = new javax.swing.JTextField();
        jTxtField_Ville = new javax.swing.JTextField();
        jTxtField_Mobile = new javax.swing.JTextField();
        jTxtField_Remarques = new javax.swing.JTextField();
        jCheckBox_CarteFidelité = new javax.swing.JCheckBox();
        jScrollPane = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLab_Fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jImprimer.setForeground(new java.awt.Color(255, 255, 255));
        jImprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/imprimer.png"))); // NOI18N
        jImprimer.setText("Imprimer");
        getContentPane().add(jImprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jBtnSauvegarder.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSauvegarder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/ajouter.png"))); // NOI18N
        jBtnSauvegarder.setText("Sauvegarder");
        getContentPane().add(jBtnSauvegarder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 40));

        jBtnAnnuler.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAnnuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/annuler.png"))); // NOI18N
        jBtnAnnuler.setText("Annuler");
        getContentPane().add(jBtnAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jApercuAvImp.setForeground(new java.awt.Color(255, 255, 255));
        jApercuAvImp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/apercu2.png"))); // NOI18N
        jApercuAvImp.setText("Aperçu avant impression");
        getContentPane().add(jApercuAvImp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 170, -1));

        jExporter.setForeground(new java.awt.Color(255, 255, 255));
        jExporter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/exporter.png"))); // NOI18N
        jExporter.setText("Exporter");
        getContentPane().add(jExporter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        JRetMenuClients.setForeground(new java.awt.Color(255, 255, 255));
        JRetMenuClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/retour.png"))); // NOI18N
        JRetMenuClients.setText("Retour au menu CLients");
        getContentPane().add(JRetMenuClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        jAjoutClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jAjoutClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/client.png"))); // NOI18N
        jAjoutClient.setText("Ajout d'un client");
        getContentPane().add(jAjoutClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 260, 70));

        jPan_AjoutClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        jPan_AjoutClient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLab.setText("Ajout, modification, suppression, consultation et impression");
        jPan_AjoutClient.add(jLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 6, 550, -1));

        jLab_Remarques.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLab_Remarques.setText("Remarques");
        jPan_AjoutClient.add(jLab_Remarques, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLab_Nom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLab_Nom.setText("Nom");
        jPan_AjoutClient.add(jLab_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLab_Code.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLab_Code.setText("Code");
        jPan_AjoutClient.add(jLab_Code, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLab_Prénom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLab_Prénom.setText("Prénom");
        jPan_AjoutClient.add(jLab_Prénom, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLab_DateCreation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLab_DateCreation.setText("Date création");
        jPan_AjoutClient.add(jLab_DateCreation, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        jLab_Adresse.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLab_Adresse.setText("Adresse");
        jPan_AjoutClient.add(jLab_Adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLab_Mobile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLab_Mobile.setText("Mobile");
        jPan_AjoutClient.add(jLab_Mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jLab_TelFixe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLab_TelFixe.setText("Tél. fixe");
        jPan_AjoutClient.add(jLab_TelFixe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLab_CodePostal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLab_CodePostal.setText("Code postal");
        jPan_AjoutClient.add(jLab_CodePostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLab_Ville.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLab_Ville.setText("Ville");
        jPan_AjoutClient.add(jLab_Ville, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        jLab_Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLab_Email.setText("Email");
        jPan_AjoutClient.add(jLab_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLab_CarteFidélité.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLab_CarteFidélité.setText("Carte fidélité");
        jPan_AjoutClient.add(jLab_CarteFidélité, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        jTxt_Adresse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTxt_Adresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_AdresseActionPerformed(evt);
            }
        });
        jPan_AjoutClient.add(jTxt_Adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 690, 20));

        jTxtField_Prénom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTxtField_Prénom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtField_PrénomActionPerformed(evt);
            }
        });
        jPan_AjoutClient.add(jTxtField_Prénom, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 330, 20));

        jTxtField_Nom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTxtField_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtField_NomActionPerformed(evt);
            }
        });
        jPan_AjoutClient.add(jTxtField_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 220, 20));

        jTxtField_Email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTxtField_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtField_EmailActionPerformed(evt);
            }
        });
        jPan_AjoutClient.add(jTxtField_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 220, 20));

        jTxtField_DateCreation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTxtField_DateCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtField_DateCreationActionPerformed(evt);
            }
        });
        jPan_AjoutClient.add(jTxtField_DateCreation, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 140, 20));

        jTxtField_Code.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTxtField_Code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtField_CodeActionPerformed(evt);
            }
        });
        jPan_AjoutClient.add(jTxtField_Code, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 220, 20));

        jTxtField_TelFixe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTxtField_TelFixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtField_TelFixeActionPerformed(evt);
            }
        });
        jPan_AjoutClient.add(jTxtField_TelFixe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 220, 20));

        jTxtField_CodePostal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTxtField_CodePostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtField_CodePostalActionPerformed(evt);
            }
        });
        jPan_AjoutClient.add(jTxtField_CodePostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 220, 20));

        jTxtField_Ville.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTxtField_Ville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtField_VilleActionPerformed(evt);
            }
        });
        jPan_AjoutClient.add(jTxtField_Ville, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 220, 20));

        jTxtField_Mobile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTxtField_Mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtField_MobileActionPerformed(evt);
            }
        });
        jPan_AjoutClient.add(jTxtField_Mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 220, 20));

        jTxtField_Remarques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtField_RemarquesActionPerformed(evt);
            }
        });
        jPan_AjoutClient.add(jTxtField_Remarques, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 680, 80));
        jPan_AjoutClient.add(jCheckBox_CarteFidelité, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, -1, -1));

        getContentPane().add(jPan_AjoutClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 860, 410));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Code", "Nom", "Prénom", "Carte Fidélité", "Date Création"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(jTable2);

        getContentPane().add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 860, 150));

        jLab_Fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.fond/fond.jpg"))); // NOI18N
        getContentPane().add(jLab_Fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_AdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_AdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_AdresseActionPerformed

    private void jTxtField_PrénomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtField_PrénomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtField_PrénomActionPerformed

    private void jTxtField_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtField_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtField_NomActionPerformed

    private void jTxtField_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtField_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtField_EmailActionPerformed

    private void jTxtField_DateCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtField_DateCreationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtField_DateCreationActionPerformed

    private void jTxtField_CodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtField_CodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtField_CodeActionPerformed

    private void jTxtField_TelFixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtField_TelFixeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtField_TelFixeActionPerformed

    private void jTxtField_CodePostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtField_CodePostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtField_CodePostalActionPerformed

    private void jTxtField_VilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtField_VilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtField_VilleActionPerformed

    private void jTxtField_MobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtField_MobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtField_MobileActionPerformed

    private void jTxtField_RemarquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtField_RemarquesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtField_RemarquesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenFicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenFicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenFicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenFicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FenFicheClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JRetMenuClients;
    private javax.swing.JLabel jAjoutClient;
    private javax.swing.JLabel jApercuAvImp;
    private javax.swing.JLabel jBtnAnnuler;
    private javax.swing.JLabel jBtnSauvegarder;
    private javax.swing.JCheckBox jCheckBox_CarteFidelité;
    private javax.swing.JLabel jExporter;
    private javax.swing.JLabel jImprimer;
    private javax.swing.JLabel jLab;
    private javax.swing.JLabel jLab_Adresse;
    private javax.swing.JLabel jLab_CarteFidélité;
    private javax.swing.JLabel jLab_Code;
    private javax.swing.JLabel jLab_CodePostal;
    private javax.swing.JLabel jLab_DateCreation;
    private javax.swing.JLabel jLab_Email;
    private javax.swing.JLabel jLab_Fond;
    private javax.swing.JLabel jLab_Mobile;
    private javax.swing.JLabel jLab_Nom;
    private javax.swing.JLabel jLab_Prénom;
    private javax.swing.JLabel jLab_Remarques;
    private javax.swing.JLabel jLab_TelFixe;
    private javax.swing.JLabel jLab_Ville;
    private javax.swing.JPanel jPan_AjoutClient;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTxtField_Code;
    private javax.swing.JTextField jTxtField_CodePostal;
    private javax.swing.JTextField jTxtField_DateCreation;
    private javax.swing.JTextField jTxtField_Email;
    private javax.swing.JTextField jTxtField_Mobile;
    private javax.swing.JTextField jTxtField_Nom;
    private javax.swing.JTextField jTxtField_Prénom;
    private javax.swing.JTextField jTxtField_Remarques;
    private javax.swing.JTextField jTxtField_TelFixe;
    private javax.swing.JTextField jTxtField_Ville;
    private javax.swing.JTextField jTxt_Adresse;
    // End of variables declaration//GEN-END:variables
}
