/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maquette;

/**
 *
 * @author Théoo
 */
public class FenFacture extends javax.swing.JFrame {

    /**
     * Creates new form FenFacture
     */
    public FenFacture() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        word = new javax.swing.JLabel();
        supprUneLigne = new javax.swing.JLabel();
        supprTouteLigne = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        barre1 = new javax.swing.JLabel();
        barre2 = new javax.swing.JLabel();
        nomCli = new javax.swing.JTextField();
        parcourirLesArticles = new javax.swing.JButton();
        modeReglement = new javax.swing.JLabel();
        selectionClient = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        etiquette = new javax.swing.JLabel();
        NumeroDoc = new javax.swing.JLabel();
        numDossier = new javax.swing.JComboBox();
        date = new javax.swing.JLabel();
        userCode = new javax.swing.JTextField();
        codeArticle = new javax.swing.JLabel();
        DesignationArticle = new javax.swing.JLabel();
        formCodeArticle = new javax.swing.JTextField();
        formDesignationArticle = new javax.swing.JTextField();
        CodeCategorieArticle = new javax.swing.JLabel();
        formCodeCategorie = new javax.swing.JTextField();
        quantiteArticle = new javax.swing.JLabel();
        formQuantiteArticle = new javax.swing.JComboBox();
        MontantArticle = new javax.swing.JLabel();
        formMontantArticle = new javax.swing.JTextField();
        ajouterArticle = new javax.swing.JButton();
        modifierArticle = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        formModeReglement = new javax.swing.JComboBox();
        ValiderFacture = new javax.swing.JButton();
        fond = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        word.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/docx.png"))); // NOI18N
        word.setText("Fichier de facture");
        getContentPane().add(word, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, 80));

        supprUneLigne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/supprimer2.png"))); // NOI18N
        supprUneLigne.setText("Supprimer une ligne de facture");
        getContentPane().add(supprUneLigne, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        supprTouteLigne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/supprimer3.png"))); // NOI18N
        supprTouteLigne.setText("Supprimmer toutes les lignes");
        getContentPane().add(supprTouteLigne, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 260, 50));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/retour.png"))); // NOI18N
        home.setText("menu principal");
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        barre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/barre.png"))); // NOI18N
        barre1.setText("jLabel1");
        getContentPane().add(barre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 740, -1));

        barre2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/barre.png"))); // NOI18N
        barre2.setText("jLabel1");
        getContentPane().add(barre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 740, -1));

        nomCli.setText("[ Cliquez ici pour sélectionner un client ]");
        nomCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomCliActionPerformed(evt);
            }
        });
        getContentPane().add(nomCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 200, -1));

        parcourirLesArticles.setText("Parcourir les articles");
        getContentPane().add(parcourirLesArticles, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        modeReglement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/carte.png"))); // NOI18N
        modeReglement.setText("Mode de réglement");
        getContentPane().add(modeReglement, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 130, 20));

        selectionClient.setText(" Nom du client");
        getContentPane().add(selectionClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 90, 30));

        total.setText("Total :");
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 40, 20));

        etiquette.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/etiquette.png"))); // NOI18N
        getContentPane().add(etiquette, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 210, 60));

        NumeroDoc.setText("Numéro du document");
        getContentPane().add(NumeroDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 110, 30));

        numDossier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        numDossier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numDossierActionPerformed(evt);
            }
        });
        getContentPane().add(numDossier, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        date.setText("Date du jour");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 90, 30));

        userCode.setText("<User Code>");
        userCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCodeActionPerformed(evt);
            }
        });
        getContentPane().add(userCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 80, -1));

        codeArticle.setText("Code");
        getContentPane().add(codeArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 50, 20));

        DesignationArticle.setText("Désignation");
        getContentPane().add(DesignationArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 70, 20));

        formCodeArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formCodeArticleActionPerformed(evt);
            }
        });
        getContentPane().add(formCodeArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 50, -1));
        getContentPane().add(formDesignationArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 300, -1));

        CodeCategorieArticle.setText("Code catégorie");
        getContentPane().add(CodeCategorieArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 80, 20));
        getContentPane().add(formCodeCategorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, 60, 20));

        quantiteArticle.setText("Quantité");
        getContentPane().add(quantiteArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 50, 20));

        formQuantiteArticle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(formQuantiteArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 40, -1));

        MontantArticle.setText("Montant");
        getContentPane().add(MontantArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 50, 20));
        getContentPane().add(formMontantArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 60, -1));

        ajouterArticle.setText("Modifier");
        getContentPane().add(ajouterArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, -1, -1));

        modifierArticle.setText("Ajouter");
        getContentPane().add(modifierArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 710, 170));

        formModeReglement.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(formModeReglement, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, -1, -1));

        ValiderFacture.setText("Validez la facture");
        getContentPane().add(ValiderFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, -1, -1));

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.fond/fondGeneral.jpg"))); // NOI18N
        fond.setPreferredSize(new java.awt.Dimension(1027, 582));
        getContentPane().add(fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -70, 1060, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomCliActionPerformed

    private void numDossierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numDossierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numDossierActionPerformed

    private void userCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userCodeActionPerformed

    private void formCodeArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formCodeArticleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formCodeArticleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenFacture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CodeCategorieArticle;
    private javax.swing.JLabel DesignationArticle;
    private javax.swing.JLabel MontantArticle;
    private javax.swing.JLabel NumeroDoc;
    private javax.swing.JButton ValiderFacture;
    private javax.swing.JButton ajouterArticle;
    private javax.swing.JLabel barre1;
    private javax.swing.JLabel barre2;
    private javax.swing.JLabel codeArticle;
    private javax.swing.JLabel date;
    private javax.swing.JLabel etiquette;
    private javax.swing.JLabel fond;
    private javax.swing.JTextField formCodeArticle;
    private javax.swing.JTextField formCodeCategorie;
    private javax.swing.JTextField formDesignationArticle;
    private javax.swing.JComboBox formModeReglement;
    private javax.swing.JTextField formMontantArticle;
    private javax.swing.JComboBox formQuantiteArticle;
    private javax.swing.JLabel home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel modeReglement;
    private javax.swing.JButton modifierArticle;
    private javax.swing.JTextField nomCli;
    private javax.swing.JComboBox numDossier;
    private javax.swing.JButton parcourirLesArticles;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JLabel quantiteArticle;
    private javax.swing.JLabel selectionClient;
    private javax.swing.JLabel supprTouteLigne;
    private javax.swing.JLabel supprUneLigne;
    private javax.swing.JLabel total;
    private javax.swing.JTextField userCode;
    private javax.swing.JLabel word;
    // End of variables declaration//GEN-END:variables
}
