/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maquette;

/**
 *
 * @author Théoo
 */
public class FenMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FenMenuPrincipal
     */
    public FenMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        camembert = new javax.swing.JLabel();
        marcheur = new javax.swing.JLabel();
        parametre = new javax.swing.JLabel();
        ordi = new javax.swing.JLabel();
        dossier = new javax.swing.JLabel();
        croix = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        camembert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.accueil/camembert.png"))); // NOI18N
        getContentPane().add(camembert, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        marcheur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.accueil/marcheur1.png"))); // NOI18N
        getContentPane().add(marcheur, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        parametre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.accueil/parametre1.png"))); // NOI18N
        getContentPane().add(parametre, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        ordi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.accueil/powerBook.png"))); // NOI18N
        getContentPane().add(ordi, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        dossier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.accueil/classeur1.png"))); // NOI18N
        getContentPane().add(dossier, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, -1, -1));

        croix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.accueil/quitter1.png"))); // NOI18N
        getContentPane().add(croix, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.fond/fondGeneral.jpg"))); // NOI18N
        getContentPane().add(fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel camembert;
    private javax.swing.JLabel croix;
    private javax.swing.JLabel dossier;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel marcheur;
    private javax.swing.JLabel ordi;
    private javax.swing.JLabel parametre;
    // End of variables declaration//GEN-END:variables
}
