/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maquette;

/**
 *
 * @author Cyril
 */
public class FenStats extends javax.swing.JPanel {

    /**
     * Creates new form FenStats
     */
    public FenStats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab_Facture = new javax.swing.JLabel();
        jLab_Nombre = new javax.swing.JLabel();
        jLab_Ca = new javax.swing.JLabel();
        jLab_Impayés = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Facture.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLab_Facture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/chart.png"))); // NOI18N
        jLab_Facture.setText("Factures");
        add(jLab_Facture, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLab_Nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLab_Nombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/ods.png"))); // NOI18N
        jLab_Nombre.setText("Nombre");
        add(jLab_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        jLab_Ca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLab_Ca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/tableauBord.png"))); // NOI18N
        jLab_Ca.setText("CA");
        add(jLab_Ca, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jLab_Impayés.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLab_Impayés.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.gestion/client2.png"))); // NOI18N
        jLab_Impayés.setText("Impayés");
        add(jLab_Impayés, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLab_Ca;
    private javax.swing.JLabel jLab_Facture;
    private javax.swing.JLabel jLab_Impayés;
    private javax.swing.JLabel jLab_Nombre;
    // End of variables declaration//GEN-END:variables
}
